language: php

sudo: false

matrix:
  include:
    - php: hhvm
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env: deps=high
    - php: 5.6
      env: deps=low
    - php: 7
  fast_finish: true

env:
    global:
        - deps=high

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - composer self-update

install:
  - if [ "$deps" = "high" ]; then composer --prefer-source update; fi;
  - if [ "$deps" = "low" ]; then  composer --prefer-source --prefer-lowest --prefer-stable update; fi;

script:
    - bin/phpspec run -v
