##
 # This file is part of CustomScripts HelpDesk project.
 #
 # (c) 2015 Pierre du Plessis <info@customscripts.co.za>
 #
 # This source file is subject to the MIT license that is bundled
 # with this source code in the file LICENSE.
 ##

CS\HelpDeskBundle\Entity\Ticket:
    type: entity
    table: helpdesk_tickets
    repositoryClass: CS\HelpDeskBundle\Repository\TicketRepository
    indexes:
        title_index:
          columns: [title]
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 125
        description:
            type: text
            nullable: true
        status:
            type: string
            length: 25